include:
  - board: seeeduino_xiao_ble
    shield: lalapadmini_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: lalapadmini_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: lalapadmini_dongle rgbled_adapter prospector_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset